version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: evidence_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cj.m9090
      POSTGRES_DB: evidence_db
    ports:
      - "5432:5432" # Se a porta 5432 já estiver em uso pelo seu Postgres local, mude para "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: